name: Build and Publish

on:
  push

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build v7 image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./7
          tags: |
            saphyel/php:7
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build v8 image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./8
          tags: |
            saphyel/php:8
            saphyel/php:latest
          push: ${{ github.ref == 'refs/heads/master' }}
